[tools]
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
gitversion = "latest"
actionlint = "latest"
aws-cli = "latest"

[settings]
experimental = true
auto_install = true

[tasks]
lint = ["golangci-lint run ./...", "goreleaser check", "actionlint"]
deps = ["go mod tidy", "go mod vendor"]
format = ["golangci-lint fmt ./..."]
tag = ["git tag v$(gitversion -config .gitversion.yml -showvariable MajorMinorPatch)"]
snapshot = "goreleaser release --snapshot"
release = "goreleaser release --clean"
dist = "aws s3 cp dist/install.sh s3://${S3_BUCKET}/${DIST_FOLDER}/install.sh --region ${AWS_REGION}"

