services:
  classifier:
    build:
      dockerfile: build/classifier
      context: .
  volumes:
    - ./config:/config 
  depends_on:
    ollama:
      condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
      - ./build/ollama:/model_files 
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URLS: http://ollama:11434
      WEBUI_URL: http://localhost:8080
      WEBUI_AUTH: false
    depends_on:
      ollama:
        condition: service_healthy
volumes:
  ollama_data:
    driver: local
  open-webui:


